### ISSUE TITLE
PR body does not support `\n` characters

### ISSUE THREAD

**Issue by educhastenier** [bonitasoft/github-workflows#5]
https://github.com/bonitasoft/github-workflows/blob/d10d9a50e54ce35744c68c2609e168c30b2a99a8/.github/workflows/_reusable_merge_upstream.yml#L88

They simply display as is.

**Comment by akantcheff** [comment]
Fixed in https://github.com/bonitasoft/github-workflows/commit/326f47d54dac017a9d15704d7555068d8ee1c888
